
# Language setting
language: go

# Version number
go:
  - 1.7.6
  - 1.8.5
  - 1.9.2

build:
  ci:
    - go version
    - go run hello-world.go
    - go build hello-world.go
    - ls
    - ./hello-world
    
jobs:
  - name: go_u16golall_Test
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
          name: version_1.7.6
          runtime:
            options:
              imageName: "drydock/u16golall"
              imageTag: "master"
          script:
            - [[ -s "$HOME/.gvm/scripts/gvm" ]] && source $HOME/.gvm/scripts/gvm
            - go use 1.7.6
            - printenv
            
resources:
  - name: sample_gol
    type: gitRepo
    integration: "github-subint"
    versionTemplate:
      sourceName: ankul-shippable/sampleGol
      branch: master
      
