
# Language setting
language: go

# Version number
go:
  - 1.7.6
  - 1.8.5
  - 1.9.2

build:
  ci:
    - go version
    - go run hello-world.go
    - go build hello-world.go
    - ls
    - ./hello-world
    
jobs:
  - name: go_u16golall_Test
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample_gol
      - TASK:
          name: version_1.7.6
          runtime:
            options:
              imageName: "drydock/u16golall"
              imageTag: "master"
          script:
            - source $HOME/.gvm/scripts/gvm
            - gvm use 1.7.6
            - cd $SAMPLE_GOL_STATE && go run hello-world.go
            - cd $SAMPLE_GOL_STATE && go build hello-world.go
            - cd $SAMPLE_GOL_STATE && ls
            - cd $SAMPLE_GOL_STATE &&./hello-world
      - TASK:
          name: version_1.8.5
          runtime:
            options:
              imageName: "drydock/u16golall"
              imageTag: "master"
          script:
            - source $HOME/.gvm/scripts/gvm
            - gvm use 1.8.5
            - cd $SAMPLE_GOL_STATE && go run hello-world.go
            - cd $SAMPLE_GOL_STATE && go build hello-world.go
            - cd $SAMPLE_GOL_STATE && ls
            - cd $SAMPLE_GOL_STATE &&./hello-world
      - TASK:
          name: version_1.9.2
          runtime:
            options:
              imageName: "drydock/u16golall"
              imageTag: "master"
          script:
            - source $HOME/.gvm/scripts/gvm
            - gvm use 1.9.2
            - cd $SAMPLE_GOL_STATE && go run hello-world.go
            - cd $SAMPLE_GOL_STATE && go build hello-world.go
            - cd $SAMPLE_GOL_STATE && ls
            - cd $SAMPLE_GOL_STATE &&./hello-world            

resources:
  - name: sample_gol
    type: gitRepo
    integration: "github-subint"
    versionTemplate:
      sourceName: ankul-shippable/sampleGol
      branch: master
      
